### ISSUE TITLE
Enlaces dentro de la guia

### ISSUE THREAD

**Issue by Vic0005** [Awoocado/guide#23]
**¿Es tu petición relacionada a un problema? Por favor describa.**

Cuando se intenta abrir cualquier enlace en la guía da un error 404
**Describa la solución que te gustaría**

Cambiar los links a las nuevas urls, en español

**Describa alternativas que hayas considerado**

También se podrían volver a poner en inglés, los nombres 
**Notas adicionales**

Ninguna

**Comment by socram03** [comment]
La mayoria de enlaces estan preparados, los demas se iran actualizando segun el contenido lo haga. Si has encontrados links rotos en especifico, dejalos en este issues

**Comment by Vic0005** [comment]
> La mayoria de enlaces estan preparados, los demas se iran actualizando segun el contenido lo haga. Si has encontrados links rotos en especifico, dejalos en este issues

Todos los de https://guia.palta.ml/ (la página de inicio)
